import Vue from 'vue';
import draggable from 'vuedraggable';
import Input from './Input.vue';
import InputSelect from './InputSelect.vue';
import ButtonWrap from './ButtonWrap.vue';
import BackNav from './BackNav.vue';
import DefaultFilterWrap from './DefaultFilterWrap.vue';
import VCCalendar from './VC-Calendar.vue';
import VCCalendarSelect from './VC-CalendarSelect.vue';
import LoadingOverlay from './Loading-Overlay.vue';
import ModalDialog from './Modal-Dialog.vue';
import Select from './Select.vue';
import Checkbox from './Checkbox.vue';
import CheckboxFull from './CheckboxFull.vue';
import Loading from './Loading.vue';
import LoaderLay from './LoaderLay.vue';
import MainBlock from './MainBlock.vue';

Vue.component('C-Input', Input);
Vue.component('C-Input-Select', InputSelect);
Vue.component('C-Button-Wrap', ButtonWrap);
Vue.component('C-Back-Nav', BackNav);
Vue.component('C-vc-calendar', VCCalendar);
Vue.component('C-vc-calendar-select', VCCalendarSelect);
Vue.component('C-Loading-Overlay', LoadingOverlay);
Vue.component('C-Loading', Loading);
Vue.component('C-LoaderLay', LoaderLay);
Vue.component('C-Modal-Dialog', ModalDialog);
Vue.component('C-Draggable', draggable);
Vue.component('C-Select', Select);
Vue.component('C-Checkbox', Checkbox);
Vue.component('C-Checkbox-Full', CheckboxFull);
Vue.component('C-Filter-Wrap', DefaultFilterWrap);
Vue.component('C-Main-Block', MainBlock);
